# Generated by Django 3.1 on 2021-12-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_close_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='close_date',
            field=models.DateTimeField(),
        ),
    ]
