# Generated by Django 3.1 on 2021-12-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20211228_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='close_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
